### ISSUE TITLE
[FEATURE]: buildtest buildspec find --buildspec-count

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1214]
### Please describe your feature request

This option `buildtest buildspec find --buildspec-count` can be used to report a count of total valid buildspecs.
```
(buildtest)  ~/Documents/github/buildtest/ [color_changes_buildtest_hy] buildtest bc summary
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                           │
│     Reading Buildspec Cache File:   /Users/siddiq90/Documents/github/buildtest/var/buildspecs/cache.json  │
│     Total Valid Buildspecs:         48                                                                    │
│     Total Invalid Buildspecs:       3                                                                     │
│     Total Unique Tags:              15                                                                    │
│     Total Maintainers:              3                                                                     │
│                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

## TODO

- [ ] Add option `--buildspec-count` in  https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py
- [ ] Implement Logic in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/buildspec.py
- [ ] Add option to [bash completion](https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh) script 
- [ ] Add regression test to verify option in https://github.com/buildtesters/buildtest/blob/devel/tests/cli/test_buildspec.py 
 

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
@jscook2345 this should be a relatively easy task as a first contribution to buildtest

**Comment by jscook2345** [comment]
If you have a summary command, why do you want to add another command to do the same thing?

**Comment by shahzebsiddiqui** [comment]
The output of `buildtest buildspec summary`  will summarize the content of the buildspec cache and display several tables which can be quite long. This feature `buildtest buildspec find --buildspec-count` is basically giving a total count of valid buildspec which should report a raw number in this case the expected output should be *48* based on the output from `buildtest buildspec summary`. 

This option would be useful to know how many buildspecs are valid for a given system without having to run `buildtest buildspec summary` and mainly used for reporting purposes, lets say an HPC site wants to know how many total tests are valid buildspecs they can just run this option to find out. I can foresee another option to query invalid buildspecs which can be used to find total count of invalid buildspecs.
