### ISSUE TITLE
Add coverage for method regex_check

### ISSUE THREAD

**Issue by prathmesh4321** [buildtesters/buildtest#1448]
### Please describe your feature

The coverage for the `regex_check()` function is missing. See https://app.codecov.io/gh/buildtesters/buildtest/blob/devel/buildtest/buildsystem/checks.py

![Screen Shot 2023-04-19 at 10 57 34 PM](https://user-images.githubusercontent.com/35829130/233271805-067b0bca-ab20-4f22-a566-287e18136ddb.png)

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
@szuananwar i will be assigning this task to you. if you have any questions please reach out or ask in #developer channel

**Comment by shahzebsiddiqui** [comment]
# TODO

- [x] Add method in https://github.com/buildtesters/buildtest/blob/devel/tests/builders/test_builders.py to test `regex_check`
- [x] Use this test https://github.com/buildtesters/buildtest/blob/devel/tutorials/test_status/status_regex.yml for your regression test. Please create a symbolic link to this file in  https://github.com/buildtesters/buildtest/blob/devel/tests/builders/

**Comment by szuananwar** [comment]
Pull request has been created.
