### ISSUE TITLE
[FEATURE]: an option to show all subcommands `--help-all`

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1453]
### Please describe your feature

currently we see all the subcommands when running `buildtest --help`

```console
COMMANDS:
  
    build (bd)          Build and Run test
    buildspec (bc)      Buildspec Interface
    config (cg)         Query buildtest configuration
    report (rt)         Query test report
    inspect (it)        Inspect a test based on NAME or ID
    path                Show path attributes for a given test
    history (hy)        Query build history
    schema              List schema contents and examples
    cdash               Upload test to CDASH server
    unittests (test)    Run buildtest unit tests
    stylecheck (style)  Run buildtest style checks
    cd                  change directory to root of test given a test name
    clean               Remove all generate files from buildtest including
                        test directory, log files, report file, buildspec
                        cache, history files.
    docs                Open buildtest docs in browser
    schemadocs          Open buildtest schema docs in browser
    debugreport (debug)
                        Display system information and additional information
                        for debugging purposes.
    stats               Show test statistics for given test
    info                Show details regarding current buildtest setup
    help (h)            buildtest command guide
    tutorial-examples   Generate documentation examples for Buildtest Tutorial

```

This is going to be an issue going forward as we add more sub-commands. We should add some option let's say `buildtest --help-all` that will show all subcommands. For instance we don't need to show `unittests`, `stylecheck` `docs` `schemadocs` and `tutorial-examples` command since they are used for development purposes. 

That being said the `buildtest --help` should show a subset of the commands and `buildtest --help-all` should show everything. 

# TODO

- [ ] Add option `--help-all` to argparse https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py
- [ ] Add option to [bash completion](https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh) script
- [ ] Add implementation for `buildtest --help-all` and change behavior of `buildtest --help`  

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
@Mendi03 i will assign this issue to you it would be an interesting task for you. I dont personally know the solution for this yet so i would recommend you get familiar with [argparse](https://docs.python.org/3/library/argparse.html) library. 

This feature was kinda inspired by spack if you do `spack help --all`
