### ISSUE TITLE
[FEATURE]: list all profiles

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1490]
### Please describe your feature

add a command `buildtest config profiles list` to report a list of profiles. The command will display a list of profiles as raw text similar to `buildtest config compilers`. 

We should have an option `--yaml` to print output of all profiles in yaml format. 
We can consider rendering output so let's have `--theme` option so we can use [rich.syntax](https://rich.readthedocs.io/en/stable/syntax.html) to print output in different themes

# TODO

- [x] Add command menu  in  argparse https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py
- [x] Add implementation https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/config.py
- [x] Add entry in `buildtest help config` https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/help.py
- [x] Add option in [bash completion](https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh) script
- [x] Add regression test in https://github.com/buildtesters/buildtest/blob/devel/tests/cli/test_config.py 
- [ ] Add documentation in https://buildtest.readthedocs.io/en/devel/configuring_buildtest.html

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
