### ISSUE TITLE
[FEATURE]: remove a profile via command line

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1491]
### Please describe your feature

adding onto feature #1490 we should have a command option `buildtest config profiles remove` that can remove an existing profile from configuration file. This can be useful way to remove a profile as pose to manually editing the file and removing the content.

This can be done with a positional argument which expects the name of profile, so let's say i want to remove `python-prof` i would do  `buildtest config profiles remove python-prof`

We can have an alias for `remove` as `rm` for accessibility. If upon removal there are no profiles we should remove the top-level key `profile` from configuration file. We can have let's say an option `-y` to accept `yes` so user can automatically confirm `yes`. If its not specified then user will be prompted to select an option like `yes/no` to remove profile. 

# TODO

- [ ]  Add command menu in argparse https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py
- [ ] Add implementation https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/config.py
- [ ] Add entry in buildtest help config https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/help.py
- [ ] Add option in [bash completion](https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh) script
- [ ] Add regression test in https://github.com/buildtesters/buildtest/blob/devel/tests/cli/test_config.py
- [ ] Add documentation in https://buildtest.readthedocs.io/en/devel/configuring_buildtest.html

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
