### ISSUE TITLE
[FEATURE]: specify alternate location where to write configuration file

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1494]
### Please describe your feature

Based on #1489 feature where we add support for saving profiles which update the configuration file. We should have an option to specify an alternate location where to store configuration file. For instance we have `buildtest config compilers find --file <file>` to specify location where to write the configuration file.

Let's create an option called `--write-config-file` in `buildtest --write-config-file build -b <b>` so if one wants to save the configuration in alternate location as part of the profile step they can do `buildtest --write-config-file /tmp/buildtest.yml bd -t python --save-profile=python-tests ` 

# TODO

- [ ] Add option `--write-config-file /tmp/buildtest.yml` in `buildtest build` command
- [ ] Add implementation support when saving profiles with `--save-profile`
- [ ] Add option to bash completion script
- [ ]  Add regression test

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
