### ISSUE TITLE
Remove option buildtest build --disable-executor-check

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1500]
@Mariamajib i am assigning this task to you

# TODO 

- [ ] Remove option from argparse file https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py
- [ ] Remove option from [bash completion](https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh) script 
- [ ] Remove logic for validation in config.py https://github.com/buildtesters/buildtest/blob/1f63db43ef2b10f40e6f18ece3ae376f5798a74e/buildtest/config.py#L122-L151
- [ ] Remove logic in main.py https://github.com/buildtesters/buildtest/blob/1f63db43ef2b10f40e6f18ece3ae376f5798a74e/buildtest/main.py#L125-L128 and remove variable in method invocation https://github.com/buildtesters/buildtest/blob/1f63db43ef2b10f40e6f18ece3ae376f5798a74e/buildtest/main.py#L135
