### ISSUE TITLE
[FEATURE]: buildtest commands

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1509]
### Please describe your feature

Let's add an option called `buildtest commands` which will show an output of  buildtest commands as a raw output. So in the `--help` we see these commands

```
COMMANDS:
  
    build (bd)          Build and Run test
    buildspec (bc)      Buildspec Interface
    config (cg)         Query buildtest configuration
    report (rt)         Query test report
    inspect (it)        Inspect a test based on NAME or ID
    path                Show path attributes for a given test
    history (hy)        Query build history
    schema              List schema contents and examples
    cdash               Upload test to CDASH server
    unittests (test)    Run buildtest unit tests
    stylecheck (style)  Run buildtest style checks
    cd                  change directory to root of test given a test name
    clean               Remove all generate files from buildtest including
                        test directory, log files, report file, buildspec
                        cache, history files.
    docs                Open buildtest docs in browser
    schemadocs          Open buildtest schema docs in browser
    debugreport (debug)
                        Display system information and additional information
                        for debugging purposes.
    stats               Show test statistics for given test
    info                Show details regarding current buildtest setup
    help (h)            buildtest command guide
    tutorial-examples   Generate documentation examples for Buildtest Tutorial
```

The output should be something like

```
$ buildtest commands
build
buildspec
config
report
inspect
path
history
schema
cdash
unittests
stylecheck
cd
clean
docs
schemadocs
debugreport
stats
info
help
tutorial-examples
```

# TODO

- [x] Add command option in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py
- [x] Add to [bash completion](https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh) script
- [x] Add implementation perhaps create a module `buildtest/cli/commands.py`
- [ ] Add regression test perhaps create a separate file in `tests/cli/test_commands.py`
- [ ] Add documentation let's put this in https://buildtest.readthedocs.io/en/devel/features.html

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
