### ISSUE TITLE
[FEATURE]: Ability to load specs in spack schema

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1533]
### Please describe your feature

We should add support for `spack load` this can be useful for running tests or simply loading the package once its installed. We should add the following. Let's say if we were to test `m4` we can load the package prior to testing it. This could be done as follows

```yaml

buildspecs:
  spack_load_example:
    type: spack
    executor: generic.local.bash
    description: "Run spack load for m4 package and run tests"
    tags: [spack]
    spack:
      root: $HOME/spack
      load:
        options: '--only package'
        specs: [m4]
      test:
        run:
          specs: ['m4']
        results:
          option: "-l"
```

In the above test, the `load` refers to `spack load` and `options` refer to options that can be passed to `spack load` command with a list of specs defined by `specs` property. The below command would translate to `spack load --only package m4`  

```yaml
      load:
        options: '--only package'
        specs: [m4]
```

The order of where `spack load` command must be written in test must be done after `spack install` (if present) and before `spack test` (if present).

# TODO

- [ ] Update [spack schema](https://github.com/buildtesters/buildtest/blob/devel/buildtest/schemas/spack.schema.json) to add support for `load` 
- [ ] Add implementation of emitting `spack load` command in https://github.com/buildtesters/buildtest/blob/devel/buildtest/builders/spack.py. This would be in method `generate_script` see https://github.com/buildtesters/buildtest/blob/58f91fdc1c1d909d12166daefd642c3ddb78c045/buildtest/builders/spack.py#L48
- [ ] Add example buildspec to demonstrate this example in https://github.com/buildtesters/buildtest/tree/devel/examples/spack
- [ ] Add valid and invalid example for testing with regression test see https://github.com/buildtesters/buildtest/tree/devel/buildtest/schemas/examples/spack.schema.json please put a valid and invalid example so we can test this works during regression test
- [ ] Add documentation in https://buildtest.readthedocs.io/en/devel/buildspecs/spack.html add this at bottom of file

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
