### ISSUE TITLE
[FEATURE]: Add support to deactivate spack environments

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1534]
### Please describe your feature

Currently we have support to create, activate and remove spack environment but not to deactivate environment `spack env deactivate`.  For reference see https://buildtest.readthedocs.io/en/devel/buildspecs/spack.html#spack-environment 

We propose to add a new feature to deactivate environment by introducing a keyword `deactivate` which is a boolean 

```yaml
buildspecs:
  spack_env_deactivate_first:
    type: spack
    executor: generic.local.bash
    description: "deactivate a spack environment first prior to activating it"
    tags: [spack]
    spack:
      root: $HOME/spack
      env:
        deactivate: true
        create:
          dir: $HOME/spack-envs/m4
        activate:
          dir: $HOME/spack-envs/m4
        specs:
          - 'm4'
      install:
        option: ''
    post_cmds: |
      spack find
      rm -rf $HOME/spack-envs/m4
```

If `deactivate: true` is set then we should emit `spack env deactivate` otherwise its not set. 

The order of the commands would be the following in this example, so we should see environment created first then we deactivate any active environment and run `spack env activate`.

```
spack env create
spack env deactivate
spack env activate
```

# TODO

- [ ] Update [spack schema](https://github.com/buildtesters/buildtest/blob/devel/buildtest/schemas/spack.schema.json) to add support for `deactivate` 
- [ ] Add implementation of emitting `spack env deactivate` command in https://github.com/buildtesters/buildtest/blob/devel/buildtest/builders/spack.py. This would be in method `generate_script` see https://github.com/buildtesters/buildtest/blob/58f91fdc1c1d909d12166daefd642c3ddb78c045/buildtest/builders/spack.py#L48
- [ ] Add example buildspec to demonstrate this example in https://github.com/buildtesters/buildtest/tree/devel/examples/spack/example 
- [ ] Add documentation in https://buildtest.readthedocs.io/en/devel/buildspecs/spack.html add this at bottom of file

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
