### ISSUE TITLE
[FEATURE]: buildtest buildspec validate by name

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1764]
### Please describe your feature

Add option ``buildtest buildspec validate -n <name>`` used for validating buildspec by name. 

This will be equivalent to how one discovers buildspec via ``buildtest build --name`` when building tests.

### Additional Information

# TODO

- [x] Add option to command line
- [x] Add to bash completion script
- [x] Add implementation in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/buildspec.py
- [x] Add regression test in https://github.com/buildtesters/buildtest/blob/devel/tests/cli/test_buildspec.py
- [x] Add documentation in https://buildtest.readthedocs.io/en/devel/gettingstarted/buildspecs_interface.html#validate-buildspecs-buildtest-buildspec-validate

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
