### ISSUE TITLE
[FEATURE]: exclude tags with 'buildtest buildspec validate'

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1766]
### Please describe your feature

Let's add a feature `--exclude-tags` to exclude tags when validating buildspecs. We should have a short option `-xt`.

# TODO
- [ ] Add command line option
- [ ] Add implementation in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/buildspec.py
- [ ] Add regression test in https://github.com/buildtesters/buildtest/blob/devel/tests/cli/test_buildspec.py
- [ ] Add to bash completion script
- [ ] Add documentation in https://buildtest.readthedocs.io/en/devel/gettingstarted/buildspecs_interface.html#validate-buildspecs-buildtest-buildspec-validate

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
this feature doesnt make sense since exclude tags work on test names and we want to operate on buildspecs
